module.exports = function () {
    return [
        { name: 'Pink', set: 'Fluorescent', color: 'ffb6d9' },
        { name: 'Orange', set: 'Fluorescent', color: 'ffdfb5' },
        { name: 'Yellow', set: 'Fluorescent', color: 'f0f4a3' },
        { name: 'Blue', set: 'Fluorescent', color: '98d5e8' },
        { name: 'Blue Green', set: 'Fluorescent', color: 'a1d0ca' },
        { name: 'Green', set: 'Cool and Refined', color: 'b0d492' },
        { name: 'Dark Blue', set: 'Cool and Refined', color: '8ea7c8' },
        { name: 'Gray', set: 'Cool and Refined', color: 'bdc7c4' },
        { name: 'Violet', set: 'Cool and Refined', color: 'b7abc8' },
        { name: 'Red', set: 'Cool and Refined', color: 'dd7e92' },
        { name: 'Smoke Blue', set: 'Warm', color: 'a9d0ce' },
        { name: 'Vermillion', set: 'Warm', color: 'ffa488' },
        { name: 'Gold', set: 'Warm', color: 'fcd97d' },
        { name: 'Magenta', set: 'Warm', color: 'e27fd2' },
        { name: 'Brown', set: 'Warm', color: 'ca9e8b' },
        { name: 'Fuchsia', set: 'Refresh Bright', color: 'f3badf' },
        { name: 'Marigold', set: 'Refresh Bright', color: 'e26650' },
        { name: 'Citrus Green', set: 'Refresh Bright', color: 'e3e766' },
        { name: 'Summer Green', set: 'Refresh Bright', color: '64bda7' },
        { name: 'Lavender', set: 'Refresh Bright', color: '64649e' },
        { name: 'Lemon Yellow', set: 'Friendly', color: 'fdf284' },
        { name: 'Apricot', set: 'Friendly', color: 'f2b071' },
        { name: 'Coral Pink', set: 'Friendly', color: 'feb2b8' },
        { name: 'Cyan', set: 'Friendly', color: '7bc9d3' },
        { name: 'Dark Gray', set: 'Friendly', color: '83827b' },
        { name: 'Copper', set: 'Neutral (US) / Natural (JP)', color: 'dfa16c', note: '(US only)' },
        { name: 'Beige', set: 'Neutral (US) / Natural (JP)', color: 'd4bd8d' },
        { name: 'Cream', set: 'Neutral (US) / Natural (JP)', color: 'f7e4bb' },
        { name: 'Cool Gray', set: 'Neutral (US) / Natural (JP)', color: 'd2d2cd' },
        { name: 'Olive', set: 'Neutral (US) / Natural (JP)', color: 'd8cf96' },
        { name: 'Dusty Pink', set: 'Neutral (US) / Natural (JP)', color: 'fcb9c2', note: '(Japan only)' },
        { name: 'Honey Orange', set: 'Gentle', color: 'f3cca3' },
        { name: 'Sherbert Yellow', set: 'Gentle', color: 'f2ee8e' },
        { name: 'Soda Blue', set: 'Gentle', color: 'a1d7e1' },
        { name: 'Lilac', set: 'Gentle', color: 'dbc1d3' },
        { name: 'Baby Pink', set: 'Gentle', color: 'f3c2ca' },
        { name: 'Iris', set: 'Calm', color: 'cdc4d6' },
        { name: 'Smoke Red', set: 'Calm', color: 'e5bdc5' },
        { name: 'Mimosa Yellow', set: 'Calm', color: 'd3ce99' },
        { name: 'Mint', set: 'Calm', color: 'c5d7d0' },
        { name: 'Moss Green', set: 'Calm', color: '96bab6' },
    ]
}